return PlaceObj('ModDef', {
	'title', "AutoExplore",
	'description', "Idle RC Explorers automatically move to discovered anomalies and research them.\n\nSagan compatible. Note though that the Sagan update introduced Rover AI similar to this mod, but unlike this mod, it requires research to become available.\n\nThe Explorer's Info Panel features an \"Auto Explore\" section that can be toggled on. In addition, each rover can be limited to certain types of anomalies via toggle buttons.\n\nIf ModConfig (Old or Reborn) is installed, the status notifications can be disabled in the Mod Config Menu.\n\nThe rover doesn't try to get to unreachable anomalies anymore and contains some elaborate custom path management so that it uses tunnels to get to its destination across maps and zones.",
	'image', "AutoExplore.png",
	'last_changes', "Handle possible invalid ModConfig configuration value.",
	'id', "Gfsiaes",
	'steam_id', "1341019047",
	'pops_desktop_uuid', "86b69af2-3522-4a5d-a52c-04c23dbdf7e8",
	'pops_any_uuid', "3956498d-f93b-4f36-bf81-08f9dc200daf",
	'author', "akarnokd",
	'version', 90,
	'lua_revision', 1007000,
	'saved_with_revision', 1008298,
	'code', {
		"Code/AutoExploreScript.lua",
		"Code/AutoPathFinding.lua",
	},
	'saved', 1634250967,
	'TagOther', true,
})