return PlaceObj('ModDef', {
	'title', "ExtractorAvailableDeposit",
	'description', "Display the available deposit under an Extractor building in the Info Panel.\r\n\r\nNotes:\r\n- The value is already visible in the rollover tooltip of the Production section in the vanilla game, this mod just makes sure it is shown in the Production section.\r\n- It mods the generic Mine-Panel and should work for custom mining buildings of other mods.",
	'image', "ExtractorAvailableDeposit.png",
	'last_changes', "Support Below and Beyond",
	'id', "hnp4m1c",
	'steam_id', "1343197684",
	'pops_desktop_uuid', "52b4f3f8-2b3c-4edc-8f72-1276e7b9ddc2",
	'pops_any_uuid', "0c741d42-541a-4e53-8a24-152bed549325",
	'author', "akarnokd",
	'version', 25,
	'lua_revision', 1007000,
	'saved_with_revision', 1007783,
	'code', {
		"Code/ExtractorAvailableDepositScript.lua",
	},
	'saved', 1631043487,
	'TagBuildings', true,
	'TagInterface', true,
})